### ISSUE TITLE
exec/nwjs not working on linux (arch)

### ISSUE THREAD

**Issue by mitjacotic** [aprilorange/nwjs#3]
I was not able to run nwjs as it was not executable because of windows file format
(^M characters as line endings)

I've opened exec file in vim, wrote
`:e ++ff=unix`
deleted all those chars, saved file and then it ran as it should. Please remove those lines and try if it works on windows, if it does, it would probably be reasonable to update the file on git.

**Comment by aprilorange** [comment]
I removed those chars locally on Windows using dos2unix command and pushed to GitHub, but it appears again when I clone it down from GitHub.

I've also updated the npm package.

**Comment by mitjacotic** [comment]
Nope, I removed the package and .../bin/exec, installed it again and it works, maybe it's just windows (editor) that adds them when you open the file:)
Thanks!
